services:
  - type: web
    name: leafscan
    env: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install gdown && pip install -r requirements.txt
    startCommand: gunicorn app:app